name: localskillconnect
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  intl: 
  flutter_rating_bar: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/intro1.png
    - assets/img/intro2.png
    - assets/img/intro3.png
    - assets/img/wallet.png
    - assets/img/bookings.png
    - assets/img/profile.png
    - assets/img/carouselimg.jpg
    - assets/img/earnings.png
    - assets/img/lostjobs.png
    - assets/img/rate.png
    - assets/img/lostjobs2.png
    - assets/img/services.png
    - assets/img/savings.png
    - assets/img/points.png
    - assets/img/reviews.png
    - assets/img/referal.png
    - assets/img/map.jpg
    - assets/img/success.png
    - assets/img/coin.png
    - assets/img/profile2.png
    - assets/img/myservices.png 
    - assets/img/mypoints.png
    - assets/img/myreviews.png
    - assets/img/mysavings.png
    - assets/img/rateit.png
    - assets/img/delete.png
    - assets/img/legal.png
    - assets/img/logout.png
    - assets/img/mylanguage.png
    - assets/img/mypassword.png
    - assets/img/pointsdeducted.png
    - assets/img/pointsadded.png
    - assets/img/red.png
    - assets/img/green.png
    

  fonts:
    - family: AveriaSerifLibre
      fonts:
        - asset: assets/fonts/AveriaSerifLibre-Bold.ttf
        - asset: assets/fonts/AveriaSerifLibre-Light.ttf